env:
  global:
   - secure: "nDBuoowqSmcjCOsK4uXfkRRGuvcLt434lXeZIND/bfOEDgOv7h62w5h4i3ebSgItWkBStLzGB8Owfb2v/S0jC+wSIoP+SD2wRg12LA0/eeb3OBYw/TR5FlCVx21/GzvODTNi8NdWb92AcYGhbLNPqMDIFHGscARjHiP2EnONhTs="

addons:
  coverity_scan:
    project:
      name: "Stellarium/stellarium"
      description: "A realistic, real-time 3D simulation of the night sky."
    notification_email: mcardinot@gmail.com
    build_command_prepend: cmake ../.
    build_command: make -j 16
    branch_pattern: master

language: cpp

compiler:
  - gcc

before_install:
  - "sudo apt-get install -qq wget make cmake"
  - "mkdir qt5"
  - "wget -q -O qt5.zip http://sourceforge.net/projects/cardinot/files/util/qt541.zip/download"
  - "unzip -qq qt5.zip -d qt5"
  - "export PATH=`pwd`/qt5/bin:$PATH"
  - "export QT_PLUGIN_PATH=`pwd`/qt5/plugins"

before_script:
  - "mkdir build"
  - "cd build"

script:
  - "cmake ../."
  - "make -j 16"
  - "sudo make install -j 16"

notifications:
  recipients:
    - mcardinot@gmail.com
  email:
    on_success: change
    on_failure: always
  irc:
    channels:
      - "irc.freenode.net#stellarium"
    template:
      - "Stellarium/trunk #%{build_number} (%{author}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
